升级最新依赖 并修复eslint报错
vbenjs/vue-vben-admin pull request #2896
Opened 2023-07-01 20:14 UTC by xingyuv

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-04 13:28 UTC, kirklin commented
vue升级3.3.4的话，unplugin-vue-define-options可以移除掉了

2023-07-04 13:31 UTC, kirklin requested changes

2023-07-04 13:31 UTC, kirklin commented on internal/ts-config/package.json
> +    "unplugin-vue-define-options": "^1.3.8",
vue3.3.4已经支持了

2023-07-04 13:31 UTC, kirklin commented on README.zh-CN.md
> +Vue Vben Admin 是一个免费开源的中后台模版。使用了最新的`vue3`,`vite4`,`TypeScript`等主流技术开发，开箱即用的中后台前端解决方案，也可用于学习参考。
vite建议可以不用指定具体版本

2023-07-04 13:55 UTC, scottMan1001 commented
能解决这个问题吗https://github.com/vbenjs/vue-vben-admin/issues/2898

2023-07-05 04:27 UTC, xingyuv commented on internal/ts-config/package.json
> +    "unplugin-vue-define-options": "^1.3.8",
done

2023-07-05 06:37 UTC, xingyuv commented
> 能解决这个问题吗#2898

解决了

2023-07-05 14:16 UTC, scottMan1001 commented
什么时候能合入呢？

2023-07-06 07:00 UTC, merged

2023-10-18 07:09 UTC, fzxiang commented
这条pr 依赖升级会引发的严重问题， 复现： clone新仓库，依赖安装完后执行lint 指令，会报如下错误
![image](https://github.com/vbenjs/vue-vben-admin/assets/38209301/d89a44ef-5b26-4919-9550-8fae4b1c800e)
stylelint 傻掉了 找不到命令。