在table组件中添加Customrender功能一样的unitComponent但是不受编辑影响，同时添加上传组件
vbenjs/vue-vben-admin pull request #3417
Opened 2023-12-13 13:06 UTC by Master-Jian

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [x] My code follows the style guidelines of this project
- [x] Is the code format correct
- [x] Is the git submission information standard?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-12-15 04:29 UTC, wangjue666 requested changes

2023-12-15 04:29 UTC, wangjue666 commented on src/views/demo/table/EditRowTable.vue
> +      unitComponent: ({ text }) => h(Image, { src: text, width: 70 }), // 显示自定义组件
我觉得不需要再增加`unitComponent`字段  已经有 `customRender` 这个字段来控制自定义渲染了

```
{
      title: '图片',
      dataIndex: 'imgs',
      width: 200,
      customRender: ({ record }) => h(Image, { src: record.imgs, width: 70 }), // 显示自定义组件
      editRow: false,
}
```

只需要改变下edit那块的渲染逻辑就好， 你认为呢

2023-12-15 06:24 UTC, Master-Jian commented on src/views/demo/table/EditRowTable.vue
> +      unitComponent: ({ text }) => h(Image, { src: text, width: 70 }), // 显示自定义组件
确实，如果能控制edit逻辑的话，不需要此字段来控制。那如何改动edit这块逻辑

2023-12-15 09:14 UTC, wangjue666 commented on src/views/demo/table/EditRowTable.vue
> +      unitComponent: ({ text }) => h(Image, { src: text, width: 70 }), // 显示自定义组件
害，有个 `editRender` 字段， 这样写就没问题


```
{
      title: '图片',
      dataIndex: 'imgs',
      width: 200,
      editRender: ({ record }) => h(Image, { src: record.imgs, width: 70 }), // 显示自定义组件
      editRow: true,
      editComponent: 'ImageUpload',
      editComponentProps: {
        api: uploadApi,
        accept: ['png', 'jpeg', 'jpg'],
        maxNumber: 1,
      },
    },
```

2023-12-15 09:14 UTC, wangjue666 commented on src/views/demo/table/EditRowTable.vue
> +      unitComponent: ({ text }) => h(Image, { src: text, width: 70 }), // 显示自定义组件
editrender 这个字段名字起的不好 乍一看还以为是可编辑情况下的自定义渲染呢

2023-12-16 01:06 UTC, BobinYang commented
BasicTable在可编辑情况下如何自定义渲染呢？

2023-12-16 01:20 UTC, wangjue666 commented
> BasicTable在可编辑情况下如何自定义渲染呢？

暂时只支持editcomponent, 太麻烦的编辑组件你或许应该考虑弄成弹窗+form表单

2023-12-16 08:17 UTC, Master-Jian commented on src/views/demo/table/EditRowTable.vue
> +      unitComponent: ({ text }) => h(Image, { src: text, width: 70 }), // 显示自定义组件
确实这名字起的不是很好，被忽略了，而且没有特别明显的标志所以我才加了这个。回头我看下

2023-12-16 08:30 UTC, closed without merging