fix: 修复搜索表单使用updateSchema时，如果使用fieldMapToTime引起的bug
vbenjs/vue-vben-admin pull request #3450
Opened 2023-12-22 01:51 UTC by zzc0217

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

当使用fieldMapToTime转换一个form表单的值时，如果有默认值的情况下，假设有一个input框在输入时需要使用updateSchema时，会把我刚选择的日期又变回默认值，这不是我预期的结果。

When using fieldMapToTime to convert the value of a form, if there is a default value, assuming there is an input box that needs to use updateScheme for input, it will change the date I just selected back to the default value, which is not the result I expected.

2023-12-22 02:26 UTC, wangjue666 commented
提供个复现代码

2023-12-22 06:14 UTC, zzc0217 commented
> 提供个复现代码

 const [registerTable, { getForm }] = useTable({
    title: '开启搜索区域',
    api: demoListApi,
    columns: getBasicColumns(),
    useSearchForm: true,
    formConfig: {
      schemas: [
        {
          field: 'date',
          label: '日期',
          component: 'RangePicker',
          defaultValue: [dayjs(), dayjs().add(1, 'day')],
        },
        {
          field: 'input',
          label: '测试input',
          component: 'Input',
          componentProps: {
            onChange() {
              getForm().updateSchema({ field: 'input' });
            },
          },
        },
      ],
      fieldMapToTime: [
        ['date', ['startTime', 'endTime'], ['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']],
      ],
    },
    showTableSetting: true,
    tableSetting: { fullScreen: true },
    showIndexColumn: false,
    rowKey: 'id',
    rowSelection: {
      type: 'checkbox',
      selectedRowKeys: state.selectedRowKeys,
      onSelect: onSelect,
      onSelectAll: onSelectAll,
    },
  }); 
先改变日期，然后输入input框就复现

2023-12-24 13:23 UTC, likui628 commented on src/components/Form/src/hooks/useFormEvents.ts
> +        !item.isUpdateNoReset &&
可是，这个值是在哪里设值的呢

2023-12-24 13:25 UTC, likui628 commented
我比较不理解的是为什么要在onChange里updateSchema，什么业务场景需要这么做呢。

2023-12-24 13:40 UTC, likui628 requested changes
主要问题是因为通过fieldMapToTime设置值之后field: 'date'值未设置
由于值未设置才导致的进入重设默认值的分支。

你可以看下handleRangeTimeValue函数

2023-12-25 01:39 UTC, zzc0217 commented on src/components/Form/src/hooks/useFormEvents.ts
> +        !item.isUpdateNoReset &&
{
field: 'date',
label: '日期',
isUpdateNoReset:true,
component: 'RangePicker',
defaultValue: [dayjs(), dayjs().add(1, 'day')],
},  这样设置，使用场景是，有三个选择框，需要选择第一个的时候，改成第二个的option，此时就需要用到updateSchema

2023-12-25 01:40 UTC, zzc0217 commented
> 主要问题是因为通过fieldMapToTime设置值之后field: 'date'值未设置 由于值未设置才导致的进入重设默认值的分支。
> 
> 你可以看下handleRangeTimeValue函数

是的，就是因为date值未设置，导致走了这里重设默认值，所以如果可以配置一个不需要update的时候设置默认值就可以解决这个问题了

2023-12-25 02:10 UTC, likui628 commented
> > 主要问题是因为通过fieldMapToTime设置值之后field: 'date'值未设置 由于值未设置才导致的进入重设默认值的分支。
> > 你可以看下handleRangeTimeValue函数
> 
> 是的，就是因为date值未设置，导致走了这里重设默认值，所以如果可以配置一个不需要update的时候设置默认值就可以解决这个问题了

是的 ，handleRangeTimeValue内的返回的values修改下就可以了

2023-12-25 02:11 UTC, zzc0217 commented on src/components/Form/src/hooks/useFormEvents.ts
> +        !item.isUpdateNoReset &&
说错了 ，是需要选择第一个的时候，改变第二个的option

2023-12-25 02:58 UTC, zzc0217 commented
> > > 主要问题是因为通过fieldMapToTime设置值之后field: 'date'值未设置 由于值未设置才导致的进入重设默认值的分支。
> > > 你可以看下handleRangeTimeValue函数
> > 
> > 
> > 是的，就是因为date值未设置，导致走了这里重设默认值，所以如果可以配置一个不需要update的时候设置默认值就可以解决这个问题了
> 
> 是的 ，handleRangeTimeValue内的返回的values修改下就可以了

那边我看了一下，好像没什么好改的，请问你这边有什么思路呢，我觉得如果加上这个配置选项会更好，因为我看handleRangeTimeValue都是在getfieldvalue或者其他获取值的时候才会调用

2023-12-25 03:58 UTC, likui628 commented
> > > > 主要问题是因为通过fieldMapToTime设置值之后field: 'date'值未设置 由于值未设置才导致的进入重设默认值的分支。
> > > > 你可以看下handleRangeTimeValue函数
> > > 
> > > 
> > > 是的，就是因为date值未设置，导致走了这里重设默认值，所以如果可以配置一个不需要update的时候设置默认值就可以解决这个问题了
> > 
> > 
> > 是的 ，handleRangeTimeValue内的返回的values修改下就可以了
> 
> 那边我看了一下，好像没什么好改的，请问你这边有什么思路呢，我觉得如果加上这个配置选项会更好，因为我看handleRangeTimeValue都是在getfieldvalue或者其他获取值的时候才会调用

我亲自尝试了发现会导致其它问题，我改了，updateSchema时只对更新的schema设置默认值

你看下解决你的问题了吗？

2023-12-25 04:01 UTC, likui628 approved these changes

2023-12-25 06:21 UTC, zzc0217 commented
> const [registerTable, { getForm }] = useTable({
> title: '开启搜索区域',
> api: demoListApi,
> columns: getBasicColumns(),
> useSearchForm: true,
> formConfig: {
> schemas: [
> {
> field: 'date',
> label: '日期',
> component: 'RangePicker',
> defaultValue: [dayjs(), dayjs().add(1, 'day')],
> },
> {
> field: 'input',
> label: '测试input',
> component: 'Input',
> componentProps: {
> onChange() {
> getForm().updateSchema({ field: 'input' });
> },
> },
> },
> ],
> fieldMapToTime: [
> ['date', ['startTime', 'endTime'], ['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']],
> ],
> },
> showTableSetting: true,
> tableSetting: { fullScreen: true },
> showIndexColumn: false,
> rowKey: 'id',
> rowSelection: {
> type: 'checkbox',
> selectedRowKeys: state.selectedRowKeys,
> onSelect: onSelect,
> onSelectAll: onSelectAll,
> },
> });


> > > > > 主要问题是因为通过fieldMapToTime设置值之后field: 'date'值未设置 由于值未设置才导致的进入重设默认值的分支。
> > > > > 你可以看下handleRangeTimeValue函数
> > > > 
> > > > 
> > > > 是的，就是因为date值未设置，导致走了这里重设默认值，所以如果可以配置一个不需要update的时候设置默认值就可以解决这个问题了
> > > 
> > > 
> > > 是的 ，handleRangeTimeValue内的返回的values修改下就可以了
> > 
> > 
> > 那边我看了一下，好像没什么好改的，请问你这边有什么思路呢，我觉得如果加上这个配置选项会更好，因为我看handleRangeTimeValue都是在getfieldvalue或者其他获取值的时候才会调用
> 
> 我亲自尝试了发现会导致其它问题，我改了，updateSchema时只对更新的schema设置默认值
> 
> 你看下解决你的问题了吗？

还是会有问题的，你这样只更新他update的值，假设我现在onchange事件里面updateSchema的是date
   formConfig: {
      schemas: [
        {
          field: 'date',
          label: '日期',
          component: 'RangePicker',
          defaultValue: [dayjs(), dayjs().add(1, 'day')],
        },
        {
          field: 'input',
          label: '测试input',
          component: 'Input',
          componentProps: {
            onChange() {
              getForm().updateSchema({ field: 'date' });
            },
          },
        },
      ],
      fieldMapToTime: [
        ['date', ['startTime', 'endTime'], ['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']],
      ],
    },
我如果是想给date加个componentProps之类的，他还是会变回默认值，我认为变回默认值这一步，应该人为去控制他要不要去恢复吧

2023-12-25 06:32 UTC, likui628 commented
要不然你提个issue吧，把你想要实现的功能详细描述下。

2023-12-25 06:42 UTC, zzc0217 commented
> @zzc0217 要不然你提个issue吧，把你想要实现的功能详细描述下。
> 
> @wangjue666 你有什么想法没

可以的 我提一下吧

2023-12-25 09:14 UTC, wangjue666 commented
> @wangjue666 你有什么想法没

明天我抽时间看下 这两天有些忙 😸

2023-12-27 02:17 UTC, wangjue666 commented
看了下 这种场景于我而言的确少见， 我一般习惯用`ifshow`来控制`schema`, 或者`updateschema`后， 再`setFieldsValue`设置下

```
formConfig: {
      schemas: [
        {
          field: 'date',
          label: '日期',
          component: 'RangePicker',
          defaultValue: [dayjs(), dayjs().add(1, 'day')],
        },
        {
          field: 'input',
          label: '测试input',
          component: 'Input',
          componentProps: {
            onChange() {
              const { updateSchema, getFieldsValue, setFieldsValue } = getForm();
              const { startTime, endTime } = getFieldsValue();
              updateSchema({ field: 'date' });
              setFieldsValue({
                date: [dayjs(startTime), dayjs(endTime)],
              });
            },
          },
        },
      ],
      fieldMapToTime: [
        ['date', ['startTime', 'endTime'], ['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']],
      ],
    },
```

2023-12-27 02:47 UTC, merged

2023-12-27 02:49 UTC, likui628 commented
> 看了下 这种场景于我而言的确少见， 我一般习惯用`ifshow`来控制`schema`, 或者`updateschema`后， 再`setFieldsValue`设置下
> 
> ```
> formConfig: {
>       schemas: [
>         {
>           field: 'date',
>           label: '日期',
>           component: 'RangePicker',
>           defaultValue: [dayjs(), dayjs().add(1, 'day')],
>         },
>         {
>           field: 'input',
>           label: '测试input',
>           component: 'Input',
>           componentProps: {
>             onChange() {
>               const { updateSchema, getFieldsValue, setFieldsValue } = getForm();
>               const { startTime, endTime } = getFieldsValue();
>               updateSchema({ field: 'date' });
>               setFieldsValue({
>                 date: [dayjs(startTime), dayjs(endTime)],
>               });
>             },
>           },
>         },
>       ],
>       fieldMapToTime: [
>         ['date', ['startTime', 'endTime'], ['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']],
>       ],
>     },
> ```

@zzc0217 我觉得 @wangjue666 说的是合理的。