feat(type->api): resultField推断api的返回值应该包含recordbale类型
vbenjs/vue-vben-admin pull request #3699
Opened 2024-03-28 01:53 UTC by electroluxcode

prop中存在resultField 这种支持xx.xx.xx类型。那么api的返回值应该包含 recordbale 类型

2024-03-28 02:01 UTC, likui628 commented
能说下这么做的原因吗？

2024-03-28 02:11 UTC, electroluxcode commented
> 能说下这么做的原因吗？

举一个例子，例如我有如下代码

```vue
<template>
  <PageWrapper title="上传组件示例">

    <BasicForm @register="register" class="my-5" />
  </PageWrapper>
</template>
<script lang="ts" setup>
  import { BasicUpload } from '@/components/Upload';
  import { useMessage } from '@/hooks/web/useMessage';
  import { BasicForm, FormSchema, useForm } from '@/components/Form';
  import { PageWrapper } from '@/components/Page';
  import { Alert } from 'ant-design-vue';
  import { uploadApi } from '@/api/sys/upload';
  const schemas: FormSchema[] = [
    {
      field: 'field2',
      component: "ApiSelect",
      label: '字段1',
      colProps: {
        span: 8,
      },
      componentProps: {
        resultField:"list",
        api: ()=>{
          return new Promise((resolve)=>{
            resolve({
              list:{
                a:[{roleName:"aa",roleValue:"aa"},{roleName:"bb",roleValue:"bb"}]
              }
            })
          })
        },
        labelField: 'roleName',
        valueField: 'roleValue',
      },
    },
  ];
  const [register,{getFieldsValue}] = useForm({
    labelWidth: 120,
    schemas,
  });
</script>
````

由于 resultfield的存在，所以这段代码是能够正常渲染的，但是目前却报错

```shell
对象字面量只能指定已知属性，并且“list”不在类型“OptionsItem[] | PromiseLike<OptionsItem[]>”中。
```

看了下源码，这部分主要是用到 lodash 的 get 从object中拿到object的嵌套数据。改成这种类型应该是符合要求

2024-03-28 02:12 UTC, electroluxcode commented
> > 能说下这么做的原因吗？
> 
> 举一个例子，例如我有如下代码
> 
> ```
> <template>
>   <PageWrapper title="上传组件示例">
> 
>     <BasicForm @register="register" class="my-5" />
>   </PageWrapper>
> </template>
> <script lang="ts" setup>
>   import { BasicUpload } from '@/components/Upload';
>   import { useMessage } from '@/hooks/web/useMessage';
>   import { BasicForm, FormSchema, useForm } from '@/components/Form';
>   import { PageWrapper } from '@/components/Page';
>   import { Alert } from 'ant-design-vue';
>   import { uploadApi } from '@/api/sys/upload';
>   const schemas: FormSchema[] = [
>     {
>       field: 'field2',
>       component: "ApiSelect",
>       label: '字段1',
>       colProps: {
>         span: 8,
>       },
>       componentProps: {
>         resultField:"list",
>         api: ()=>{
>           return new Promise((resolve)=>{
>             resolve({
>               list:{
>                 a:[{roleName:"aa",roleValue:"aa"},{roleName:"bb",roleValue:"bb"}]
>               }
>             })
>           })
>         },
>         labelField: 'roleName',
>         valueField: 'roleValue',
>       },
>     },
>   ];
>   const [register,{getFieldsValue}] = useForm({
>     labelWidth: 120,
>     schemas,
>   });
> </script>
> ```
> 
> 由于 resultfield的存在，所以这段代码是能够正常渲染的，但是目前却报错
> 
> ```shell
> 对象字面量只能指定已知属性，并且“list”不在类型“OptionsItem[] | PromiseLike<OptionsItem[]>”中。
> ```
> 
> 看了下源码，这部分主要是用到 lodash 的 get 从object中拿到object的嵌套数据。因此改成这种recordable 这种类型应该是符合要求的

2024-03-28 02:38 UTC, likui628 commented
> 
> ```shell
> 对象字面量只能指定已知属性，并且“list”不在类型“OptionsItem[] | PromiseLike<OptionsItem[]>”中。
> ```
> 
> 看了下源码，这部分主要是用到 lodash 的 get 从object中拿到object的嵌套数据。因此改成这种recordable 这种类型应该是符合要求

其实只需要把自身的api结果重现map一下就可以了
```
componentProps: {
      resultField: 'list.a',
      api: () => {
        return new Promise((resolve) => {
          resolve([
            { roleName: 'aa', roleValue: 'aa' },
            { roleName: 'bb', roleValue: 'bb' },
          ]);
        });
      },
      labelField: 'roleName',
      valueField: 'roleValue',
    },
```

2024-03-28 02:44 UTC, electroluxcode commented
> > ```shell
> > 对象字面量只能指定已知属性，并且“list”不在类型“OptionsItem[] | PromiseLike<OptionsItem[]>”中。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看了下源码，这部分主要是用到 lodash 的 get 从object中拿到object的嵌套数据。因此改成这种recordable 这种类型应该是符合要求
> 
> 其实只需要把自身的api结果重现map一下就可以了
> 
> ```
> componentProps: {
>       resultField: 'list.a',
>       api: () => {
>         return new Promise((resolve) => {
>           resolve([
>             { roleName: 'aa', roleValue: 'aa' },
>             { roleName: 'bb', roleValue: 'bb' },
>           ]);
>         });
>       },
>       labelField: 'roleName',
>       valueField: 'roleValue',
>     },
> ```

我理解你的意思，但是您的这种写法相当于否定了resultField 的存在的意义。在你目前这种写法下面,只有把resultField删掉才能够正常回显

2024-03-28 10:26 UTC, likui628 requested changes
懂你的意思了，稍微简化一下吧
```
PropType<(arg?: any) => Promise<OptionsItem[] | Recordable>>
```

2024-03-29 01:06 UTC, electroluxcode commented
> 懂你的意思了，稍微简化一下吧
> 
> ```
> PropType<(arg?: any) => Promise<OptionsItem[] | Recordable>>
> ```

okok

2024-03-29 01:08 UTC, likui628 approved these changes

2024-03-29 01:09 UTC, merged